### ISSUE TITLE
Standalone Vue.js

### ISSUE THREAD

**Issue by ansien** [locoslab/vue-typescript-component-example#1]
Is there any way to use this with the standalone version of Vue?

I tried setting an alias with aliasify but that doesn't seem to work.

I'd like to use components in my HTML which the runtime version doesn't support.

**Comment by locobert** [comment]
Using aliasify with the following config 'worked' for me in the sense that the bundle `debug/index.js` includes `vue/dist/vue.js` instead of `vue/dist/vue.common.js`. I have not tested any extended functionality.
Config changes in `package.json`
- in `devDependencies` add `"aliasify": "^2.0.0",`
- `browserify`:

``` json
  "browserify": {
    "transform": [
      "vueify",
      "aliasify"
    ]
  },
```
- new key for the aliasify config

``` json
  "aliasify": {
    "aliases": {
      "vue": "vue/dist/vue.js"
    },
    "verbose": true,
    "appliesTo": {
      "includeExtensions": [".js", ".vue", ".ts"]
    }
  }
```

`npm start` shows then 9 instances of aliasify 'replacing vue with vue/dist/vue.js of function require'
