### ISSUE TITLE
impressive

### ISSUE THREAD

**Issue by davidmoshal** [locoslab/vue-typescript-component-example#23]
Hi, discovered this while looking for a way to upgrade a TS/Vue project to include Jest for testing.

After exhausting all of the Webpack-based templates, I found your project, and after having initially being reluctant to let go of Webpack, I have to say that it's not been a problem. 

Hot replacement actually seems to work better with the browserify approach, and complilation is faster.

Thanks

David

**Comment by davidmoshal** [comment]
so, noticing a few things with this library, though it's possible that I misunderstand.

By way of background, I'm coming from vue-typescript from @itsFrank.   
That library appears abandoned at Vue 1.

In that library, the ts files are primary, and reference vue templates and/or included template scripts.  
Notably: all of the components can be included once, in the index.ts file, which makes the code more consise.

However, in vue-typescript-component, the .vue files are primary, and they reference their associated typescript files, correct?

Additionally, typescript doesn't seem to work in the script segment of the vue files, so 2 files (.vue and .ts) are required for each component, correct?

I think my personal preference would be for a single .tsx file if possible, or at least to be able to include template strings in the .ts file. Is that doable?

Dave

**Comment by locobert** [comment]
Hi David,

thanks!

Regarding your questions: it is noteworthy to distinguish between VTS (vue-typescript-component) and how we use it in this example. VTS should be mostly agnostic: it is possible to provide the template string via browserify/webpack or - similarily to the introductory example of [vue-typescript](https://github.com/itsFrank/vue-typescript) -  via `@vts.component({template: '...'})`. However, we use (and recommend) a vueify/vue-loader setup to get HMR - and for Vue.js 2 build-time template compilation. And the use of vueify/vue-loader implies the `.vue` files being primary. Additionally, having one `.vue` file per component fosters modularity. 

Regarding using TypeScript code inline in `.vue` files: we've spent some time investigating this issue, but getting IDE support would require significant effort. With the current setup we have good IDE support in both Atom and VS Code as well as source maps. And for larger components, having separate files has worked out well for us. However, this issue is again mostly orthogonal to VTS itself. If you are really invested in this, you might have a look at the 'typescript' branch in our vueify [fork](https://github.com/locoslab/vueify/tree/typescript). I've actually implemented support for TypeScript code in `.vue` files there. However, the IDE issue on the one hand, and on the other hand the limitations of the TypeScript API ('transform') used, which does not issue semantic errors, led to abandoning this effort.

So in general, I think is should be possible to use VTS mostly as a drop-in replacement for @itsFrank's version - with the caveat that the component must be explicitly registered. However, I would really recommend following the `.vue` file setup proposed by Vue.js primarily to get HMR.

**Comment by davidmoshal** [comment]
Thanks for the awesome reply. I'll respond to each of the issues separately.

a) hmr:
 - with the @itsFrank library I'm using `template: component.hbs` and there is no problem with HMR. I'm also pretty sure that *.vue files have no problem with hmr (isn't that what vue-loader does?), so I'm surprised that this is an issue.

b) inlining typescript:

- I use Webstorm, and its vue ide plugins are old (one is very old), so it has no concept of `<script lang="ts">` best it can do is es6, and possibly Flow, but it doesn't like Typsecript types in script blocks as far as I can tell.

- the [av-ts](https://github.com/HerringtonDarkholme/av-ts) library is interesting. It allows Typescript in the script blocks. So even though Webstorm does not like the typing you can use the ES6 features. That library has a [template](https://github.com/HerringtonDarkholme/av-ts-template) btw.

- the problem with av-ts libary is that there are no examples of end-to-end testing in Typescript, so that doesn't solve my goal of: **Vue + Typescript + end-2-end-testing**. I haven't been able to figure out how to include Typescript in that workflow, and resorting to a separate compilation process, e.g. using TS compiler doesn't seem like a good way to go about testing. 

c) TSX files:

- Given that Webstorm (and other IDEs) aren't yet able to handle inline typescript, my next thought was *.tsx for single vue components in TS. Problem here is that TSX doesn't seem to like the `{{}}` delimiters.

So, given all of the above, I settled on @itsFrank with TS files as primary, and *.hbs templates, though that has limited me to Vue1.x.

**Comment by davidmoshal** [comment]
BTW, Vue seems very close to a suggestion I made to Rich Harris back in 2013:

https://github.com/ractivejs/ractive/issues/299

**Comment by davidmoshal** [comment]
re-reading the av-ts comparison to yours and other frameworks:   
https://github.com/HerringtonDarkholme/av-ts/issues/7

from what he says, av-ts and vue-typescript-component are pretty similar, no?

lastly: any thoughts on [vue-class-component](https://github.com/vuejs/vue-class-component)?
seems like Evan You is commiting to that project, no?


Dave

**Comment by locobert** [comment]
Ok, let me also break it down a little.

HMR: My point was exactly that HMR works with `*.vue` files using vueify/vue-loader. That is the main reason why we use `.vue` files as the primary component files. My issue is with using the `template: '...'` approach: I've tried <https://github.com/itsFrank/vue-typescript-seed>, but HMR was not working for me (live-reload yes, but not state preserving HMR).

av-ts: I've never tried it, but I've read the comparison as well and I agree that the libraries seem pretty similar, with the author correctly highlighting his focus on extensibility.

vue-class-component: thanks for the heads up. I was not aware of the TypeScript support. After a quick look, the only negative thing I see is the need for declaring a property 2 times (cf. [example.ts](https://github.com/vuejs/vue-class-component/blob/master/example/example.ts)).

Inlining TypeScript:
I would like to distinguish 2 issues: building and IDE support. I have seen (but never tried) vue-ts-loader and as I wrote before, we got building to work with vueify. However, IDE support is essential for us.

Regarding this, I consider 3 levels of IDE support:
1. syntax highlighting of the script block
2. semantic support (code completion, live error display) for the script block
3. semantic support for the template block based on the script block

There are plugins for various editors providing Level 1 for JavaScript. I am not aware of a solution for Level 3. And I am not aware of a solution for Level 2 for TypeScript code. However, by putting the TypeScript code in separate files (as in this example), we get Level 2 support using Atom and VS Code, and I assume also Webstorm.

Regarding purity and elegance, I can certainly understand your wish to use single-file components with inline TypeScript code and I've spent some time trying to get it to work myself. However, we settled on our current model that gives us good IDE support. And as soon as the components get bigger (a couple of 100 LOC), we find having 2 files per component does not feel like a big overhead anymore. Indeed, it has also some advantages with regards to separation of code and template and the possibility to use different templates with the same code.

**Comment by davidmoshal** [comment]
thanks for the thorough response.

1) regarding itFrank and HMR:

Yes, I definitely have HMR working. But note: I'm NOT using *.vue files at all (for the reasons pointed out in your levels 1-3). Instead I use Typescript classes, with hbs templates. That way I get about as good an experience as possible. ie: changes to the *.hbs templates will hot reload, and I get semantic highlighting of the css and html in the template from Webstorm, as well as the ability to jump to css class definitions from the template, etc.

The key to the hot-reloading (which I don't think is specific to @itsFrank's library) is to include the following in the bottom of each TS file:

```ts
declare var module: any
if( module.hot ){
  const api = require('vue-hot-reload-api')
  const Vue = require('vue')
  api.install(Vue)
  if( !module.hot.data ){
    api.createRecord("<ClassName>", <ClassName>)
  }
  else{
    api.update("<ClassName>", <ClassName>)
  }
}
```

I use a Webstorm 'live template' to create these files and so that part is created automatically.

2) Regarding your levels, for Webstorm:

- Level 1:  syntax highlighting of the script block
   - Webstorm has a global setting for the javascript level of the project, including script blocks.
   - es6 (and flow) are supported.
   - I set it to es6, so conceivably I'd get partial ts support (excluding types)
   - most likely there is a way to set script blocks to ts, but I've not found it.

- Level 2:  semantic support (code completion, live error display) for the script block
   - so Webstorm is quite good at this, older versions used to require inclusion of ts definition files manually, but I think the latest version just picks them up from the package.json, ie: @types/lodash for example seems to work. I've not really pursued this so I could be wrong.
   - this works for ES5 too, it's something that Webstorm has tried hard to do.
   - ie: with an ES5 projects there has long been a way to include TS definition files and get semantic support.

- Level 3: semantic support for the template block based on the script block
  - I've never seen that work, pretty sure Webstorm has no idea what's going on inside `{{}}` in a template, be it *.hbs or *.vue !
  - would require a significant upgrade to the IntelliJ Vue plugin.
  - that's actually something I might tackle one day.

**Comment by davidmoshal** [comment]
regarding av-ts note that, like vue-class-component, typescript compiler can be used instead of babel. I'm not sure of the pros/cons, but it seems like a benefit.

 Sample templates from both projects have these deps (no babel):


1) vue-class-component, using this template: https://github.com/ktsn/typescript-webpack-simple:
```json
  "dependencies": {
    "vue": "^2.1.0",
    "vue-class-component": "^4.3.0"
  },
  "devDependencies": {
    "cross-env": "^3.0.0",
    "css-loader": "^0.25.0",
    "file-loader": "^0.9.0",
    "ts-loader": "^1.2.0",
    "typescript": "^2.0.0",
    "vue-loader": "^10.0.0",
    "vue-template-compiler": "^2.1.0",
    "webpack": "^1.13.0",
    "webpack-dev-server": "^1.16.0"
  }
```

2) av-ts using this template: https://github.com/HerringtonDarkholme/vue-ts-example
```json
  "dependencies": {
    "av-ts": "^0.5.0",
    "vue": "^2.0.3"
  },
  "devDependencies": {
    "cross-env": "^3.0.0",
    "css-loader": "^0.25.0",
    "typescript": "^2.0.3",
    "vue-loader": "^9.5.1",
    "vue-ts-loader": "0.0.3",
    "webpack": "^1.13.2",
    "webpack-dev-server": "^1.14.1"
  }
```

Note, there is a comment in the vue-class-component issues from @HerringtonDarkholme (the creator of av-ts) suggesting that vue-ts-loader should not be used. 
https://github.com/vuejs/vue-class-component/issues/49

> Please use the official ts-loader. Vue support has been merged. https://github.com/TypeStrong/ts-loader#appendtssuffixto-regexp-default

However, it's not clear if he's referring to av-ts or vue-class-component (the comment is in the vue-class-component issue list, but might be referring to av-ts).

**Comment by davidmoshal** [comment]
regarding vue-class-component declaring property twice, that doesn't appear to be the case, now sure why it's in that example:

https://github.com/vuejs/vue-class-component
> Computed properties can be declared as class property accessors.

**Comment by locobert** [comment]
So, now I am not sure what the question is any more :)

Regarding the 4 libraries: I have looked at vue-typescript. I was not aware of av-ts and the TypeScript support of vue-class-component when starting VTS and have not tried them. 

In general, I think all 4 libraries are similar in that they create an object that can be used as the 'options object' for calling [`Vue.component`](https://vuejs.org/v2/api/#Vue-component). If I remember correctly, vue-typescript also performs this registration call. VTS does not. I don't know about the other 2.

Additionally, parts of this 'options object', e.g., the template string, can be specified using the top-level component annotation.

For me, HMR, build-time compilation of the template, and inline TS code in `.vue` files seem to be independent of the library.

The setup we use (and show in this example), lets us re-use the functionality of vueify (HMR, template compilation, various languages for the template and style part). I assume that with small changes, the two other Vue.js 2 libraries could be used instead of VTS.

However, it seems that you have found a nice setup that works well. From what I understand, it seems that all three Vue.js 2 libraries should be suitable as a replacement for vue-typescript. For VTS, the main difference would be that you have to make the `Vue.component` or `Vue.extend` call explicitly with the `Foo.vueComponentOptions` object (for a class `@vts.component() class Foo ...`). Additionally, for Vue.js 2 in general, you have to make sure to include the 'full' Vue version, as the default for bundler environments uses build-time template compilation and does not support a template string.


Regarding vue-class-component declaring property twice: I am talking about the Vue.js props (not the computed properties). In the [example](https://github.com/vuejs/vue-class-component/blob/master/example/example.ts): propMessage.

**Comment by davidmoshal** [comment]
from av-ts a few minutes ago:

> please use vue-class-component. It is officially supported.

https://github.com/HerringtonDarkholme/av-ts/issues/7#issuecomment-269569193

**Comment by davidmoshal** [comment]
re propMessage, yes, I saw that in the example, but have verified that you only need it in one place.
I'm not sure what the behaviour is in two places, ideally it should complain.
given that vue-class-component is 'officially supported' (ie: Evan is contributing) and that it seems fine without Babel, I'm going to try that first.
Thanks for your help with this. 
The issue of Vue2+TS2+testing remains unresolved though...
Dave

**Comment by HerringtonDarkholme** [comment]
I don't mean to denigrate @locobert your effort, sorry for the straight tune.
Yet the official vue-class-component is good enough compared to other libraries, and it is more robust.

For example, property initialization cannot use property as data, if I read [the code](https://github.com/locoslab/vue-typescript-component/blob/master/src/vue-typescript-component.ts#L108) correctly.  Also, vue-class-component has supported custom decorator.

The official decorator library has changed a lot recently, it covers most use case and is more tested. Other decorator libraries don't have significant advantage (except several hacky shortcuts).
If we can concentrate more TS users' power on one single library, we can develop a more mature library.

**Comment by davidmoshal** [comment]
@HerringtonDarkholme I really appreciate this response, thanks.

Can I ask you to make a note on your Readme to that effect, ie: that the av-ts library is deprecated in favor of the official effort, it would safe folks the trouble of evaluating all of these libraries :).

Also, I agree 100% regarding focusing on a single official library as there are still significant challenges. 

For example, as far as I know there is no template with Vue2 + TS2 + headless browser testing of components, for example with Selenium, Jest, or equivalent, using the Typescript compiler instead of Babel. 

So this requires evaluation of the various libraries in js and figuring out where to plug them into the workflow.

**Comment by locobert** [comment]
Thanks to both of you for making me aware of the development of vue-class-component. I will certainly have a look.
